Vera98d
CodersCamp2021/team-jo-project-1 pull request #16
Opened 2021-12-05 13:19 UTC by vera98d

2021-12-08 19:33 UTC, janowsiany requested changes
It was not included in the design but could you please add a footer element with styles? Only requirement is that if there is not enough content to fill the whole page, the footer should stick to the bottom of the page

2021-12-08 19:33 UTC, janowsiany commented on index.html
> +    </div>
I imagine the markup like:
```html
<body>
  <header>...</header>
  <main>
    <div class="content">...</div>
    <aside>...</aside>
  </main>
  <footer>...</footer>
</body>
```
this will limit the level of nesting. Also when you need to pick a tag just for scripting/styling then choose div simply, section has its own semantic meaning

2021-12-12 12:56 UTC, vera98d commented on style.css
> +}
'a' has property cursor: pointer by default

2021-12-13 18:46 UTC, janowsiany commented on style.css
> +  --green1: #17a184;
```suggestion
  --greenSecondary: #17a184;
```

2021-12-13 18:46 UTC, janowsiany commented on style.css
> +  --orange1: #f27757;
```suggestion
  --orangeSecondary: #f27757;
```

2021-12-13 18:47 UTC, janowsiany approved these changes

2021-12-13 18:47 UTC, janowsiany commented on style.css
> +}
I guess we can remove that also

2021-12-13 19:23 UTC, merged