Implement rendering Header + add clock to Header.js - work in progress
CodersCamp2021/team-jo-project-1 pull request #17
Opened 2021-12-05 16:01 UTC by JaCoWymowny

2021-12-10 22:22 UTC, janowsiany requested changes
Remove unneecssary parts relateed with moment and dependencies

2021-12-10 22:22 UTC, janowsiany commented on src/components/Timer.js
> +  }
```suggestion

  render() {
    this.ref.innerHTML = `
    <span>${new Date().toLocaleTimeString()}</span>
    `;
    setTimeout(() => this.render(), 1000);
  }
```
`props` was not used so, we can skip it it
`currentTime` could be onelined

2021-12-10 22:22 UTC, janowsiany commented on src/components/Header.js
> +    <div class="header-content">
use camelCase for class names

2021-12-10 22:22 UTC, janowsiany commented on src/components/Header.js
> +      </div>
Could you please turn it into img element, please choose some picture as a logo for our app 🙏

2021-12-12 15:01 UTC, JaCoWymowny commented on src/components/Header.js
> +      </div>
ok, logo edited and added.

2021-12-12 15:01 UTC, JaCoWymowny commented on src/components/Header.js
> +    <div class="header-content">
done

2021-12-12 15:01 UTC, JaCoWymowny commented on src/components/Timer.js
> +  }
code edited.

2021-12-15 17:17 UTC, janowsiany requested changes
Please aliign your code with changes which are already on `main` branch

2021-12-15 17:17 UTC, janowsiany commented on index.js
> +});
```suggestion
import Header from "./src/components/Header.js";
import Timer from "./src/components/Timer.js";

const header = new Header();
header.render();
const timer = new Timer();
timer.render();
```
running code on load event is not necessary when we use `script` tag with `type="module"`

2021-12-16 16:38 UTC, JaCoWymowny commented on index.js
> +});
branch updated

2021-12-16 17:22 UTC, janowsiany requested changes
This is how it looks on small mobile screens, it is not acceptable, please make it responsive.
![image](https://user-images.githubusercontent.com/17599228/146418788-5859b817-4abf-41e8-b222-364c5ea8d355.png)

Also, i think that you need to fix styles for `header > *, footer > *` which might be broken because the font color is not changed to white 🤔

2021-12-16 17:22 UTC, janowsiany commented on style.css
> +  background-image: url("/src/components/logo.png");
This logo img does not look best, could you please search for some alternatives? Try `free cutlery logo svg` in Google

2021-12-16 17:22 UTC, janowsiany commented on style.css
> +  h1 {
You should not modify global styles just for your use case, it would affect all `h1` elements, instead prepare styles only for you specific element

2021-12-18 13:45 UTC, janowsiany approved these changes
👏

2021-12-18 14:25 UTC, merged