created LatestRecipesComponent
CodersCamp2021/team-jo-project-1 pull request #18
Opened 2021-12-08 00:10 UTC by stimon27

2021-12-08 22:57 UTC, janowsiany requested changes
Lets use camelCase for css class names in all placcces

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +    this.props = props;
I prefer if props were not assigned on the class instance, the only purpose for that is to share the value of props across methods which you might easily achieve by passing them as method arguments, isn't it?

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +    this.recipesList = this.ref.querySelector(".recipes-list");
Same as above, please share recipes list via method arguments, not by sharing on the class instance

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +    this.pagesWrapper = this.ref.querySelector(".pages-wrapper");
Same as above, please share the pages wrapper via method arguments, not by sharing on the class instance. Consider renaming it to something like pagination container 🤔

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +        <div class='recipes-list'></div>
I think that for list we should use `ul` element

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +    leftButton.innerHTML = '<i class="fa-solid fa-square-left"></i>;';
is that semicolon expected?

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +    rightButton.innerHTML = '<i class="fa-solid fa-square-right"></i>;';
is that semicolon expected?

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +  }
How about moving the logic from here to renderBase, instead adding following code:
```js
handlePageChange(nextPage, props, info, leftButton, rightButton) {
    const maxPage = Math.ceil(props.latestRecipies.length / 7)
    if (nextPage === 1) {
      leftButton.disabled = true;
    } else if (nextPage + 1 === maxPage) {
      rightButton.disabled = true;
    }
    info.innerText = `Page ${nextPage} of ${maxPage}`;
    this.#renderRecipesList(props);
  }
```
this will limit number of rerenders for pagination elements

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +  renderBase(props) {
Let's rename it to simple `render` so all our components have same interface

2021-12-08 22:57 UTC, janowsiany commented on index.js
> +  }
Not sure which one is more readable but i try not to use imperative for statement
```suggestion
  #renderRecipesListElements(recipesList, props, nextPage) {
    recipesList.innerHTML = "";
    const cursor = (nextPage - 1) * 2
    recipiesToBeRendered = props.latestRecipies.slice(cursor, cursor + 2)

    recipiesToBeRendered.forEach(r => {
      ...
    })
  }
```

2021-12-09 16:58 UTC, stimon27 commented on index.js
> +    this.props = props;
Props are no loger assigned on the class instance. They are passed as method arguments instead.

2021-12-09 17:03 UTC, stimon27 commented on index.js
> +    this.recipesList = this.ref.querySelector(".recipes-list");
Same change as above.

2021-12-09 17:12 UTC, stimon27 commented on index.js
> +    this.pagesWrapper = this.ref.querySelector(".pages-wrapper");
Same change as above, renaming.

2021-12-09 17:27 UTC, stimon27 commented on index.js
> +        <div class='recipes-list'></div>
Added `<ul>` element.

2021-12-09 17:28 UTC, stimon27 commented on index.js
> +    leftButton.innerHTML = '<i class="fa-solid fa-square-left"></i>;';
Fixed.

2021-12-09 17:28 UTC, stimon27 commented on index.js
> +    rightButton.innerHTML = '<i class="fa-solid fa-square-right"></i>;';
Fixed.

2021-12-09 17:28 UTC, stimon27 commented on index.js
> +  renderBase(props) {
Done.

2021-12-09 22:32 UTC, stimon27 commented on index.js
> +  }
I have two questions: 
What makes buttons `enabled` again?
Why is it nextPage + 1?

2021-12-09 22:33 UTC, stimon27 commented on index.js
> +  }
Could you please explain this cursor thing?

2021-12-10 19:53 UTC, janowsiany commented on index.js
> +  }
Good points ;), i forgot about `enabled`. I think it is good to do it like this:
```js
const maxPage = ...
leftButton.disabled = false;
rightButton.disabled = false;
if ...
```
and with `nextPage + 1 === maxPage` you are right it should be simply `nextPage === maxPage`, right?

2021-12-10 22:27 UTC, janowsiany commented on index.js
> +  }
`cursor` is a common name in the industry to point specific element in the collection. In the code above cursor point to the first element of the page which should be ended.
Treat this comment as optional, I just wanted to show another approach different than old-style imperative for statement

2021-12-10 22:34 UTC, janowsiany requested changes
One of the requirements was to expect props to be of shape  `{ latestRecipies: []{ title: string } }`, could you please adjust the code 🙏 ?

2021-12-14 18:35 UTC, janowsiany requested changes

2021-12-14 18:35 UTC, janowsiany commented on index.js
> +    this.#handlePageChange();
this is missing some arguments

2021-12-14 18:37 UTC, janowsiany requested changes

2021-12-14 18:37 UTC, janowsiany commented on index.js
> +    }
```suggestion
    leftButton.disabled = this.currentPage === 1;
    rightButton.disabled = this.currentPage === maxPage;
```

2021-12-14 19:33 UTC, janowsiany approved these changes

2021-12-15 14:40 UTC, merged