List of ingredients
CodersCamp2021/team-jo-project-1 pull request #21
Opened 2021-12-09 19:32 UTC by natimati

2021-12-13 20:32 UTC, janowsiany requested changes

2021-12-13 20:32 UTC, janowsiany commented on list.js
> +class Component {
move the file to src/components/currentRecipe.js
```suggestion
class CurrentRecipe {
```

2021-12-13 20:32 UTC, janowsiany commented on list.js
> +    this.container = document.getElementById("ingredients-list");
```suggestion
    this.ref = document.getElementById("ingredientsList");
```
we call it `ref` in other places and we use camelCase for classnames

2021-12-13 20:32 UTC, janowsiany commented on list.js
> +        input.value = "";
does calling reset method will have the same effect?

2021-12-13 20:32 UTC, janowsiany commented on index.html
> +    <script src="list.js" defer></script>
For now lets remove changes to that file

2021-12-14 20:17 UTC, natimati commented on list.js
> +        input.value = "";
I checked but input wasn't cleared after using reset method

2021-12-15 08:29 UTC, janowsiany requested changes
If we already have basic layout prepared by Weronika, can you please add `ingredientsList` to index.html so it actually works?

2021-12-15 08:29 UTC, janowsiany commented on list.js
> +    // removeButton.innerText = "remove ingredient"; //TODO: use icon
can we removve it please

2021-12-15 08:29 UTC, janowsiany commented on list.js
> +    this.container = document.getElementById("ingredients-list");
this is still to be fixed

2021-12-15 08:29 UTC, janowsiany commented on list.js
> +class Component {
this is still to be fixed

2021-12-15 08:29 UTC, janowsiany commented on list.js
> +newComponent.render({ currentRecipe: { ingredients: ["orange", "potato"] } });
move initialization to index.js

2021-12-15 21:34 UTC, natimati commented
@janowsiany please take a look, I fixed all issues

2021-12-15 21:50 UTC, janowsiany requested changes

2021-12-15 21:50 UTC, janowsiany commented on src/CurrentRecipe.js
> +class CurrentRecipe {
please move it to correct destination https://github.com/CodersCamp2021/team-jo-project-1/pull/21#discussion_r768094668

2021-12-16 16:50 UTC, natimati commented on src/CurrentRecipe.js
> +class CurrentRecipe {
done

2021-12-16 17:09 UTC, janowsiany approved these changes

2021-12-16 18:24 UTC, merged