adding SpoonacularService to get data from server
CodersCamp2021/team-jo-project-1 pull request #39
Opened 2021-12-28 20:05 UTC by natimati

2021-12-30 08:30 UTC, janowsiany requested changes

2021-12-30 08:30 UTC, janowsiany commented on src/services/SpoonacularService.js
> +  }
```suggestion
  constructor(store) {
    this.apiKey = undefined;
    store.onChange((props) => {
      if (props.token && this.apiKey !== props.token) {
        this.apiKey = props.token;
      }
    });
  }
```

2021-12-30 08:30 UTC, janowsiany commented on src/services/SpoonacularService.js
> +    }
```suggestion
    if (!this.apiKey) {
      throw new Error("`apiKey` is required");
    }
```

2021-12-30 08:30 UTC, janowsiany commented on src/services/SpoonacularService.js
> +  }
Could you please use async await syntax https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function 
this would make the functions easier to read, wdyt?

2021-12-30 23:00 UTC, natimati commented on src/services/SpoonacularService.js
> +    }
i used promise.reject for this - thanks to that function will always return a promise

2021-12-31 14:18 UTC, natimati commented on src/services/SpoonacularService.js
> +  }
done :)

2021-12-31 17:13 UTC, janowsiany requested changes

2021-12-31 17:13 UTC, janowsiany commented on src/services/SpoonacularService.js
> +        }),
```suggestion
        ingredients: recipe.usedIngredients.map(({ name }) => name),
```

2021-12-31 17:13 UTC, janowsiany commented on src/services/SpoonacularService.js
> +    });
```suggestion
    const recipesIds = data.map(({ id }) => id);
```

2021-12-31 17:13 UTC, janowsiany commented on src/services/SpoonacularService.js
> +    return recipesWithInstructions;
move this part to separete function `findRecipesWithInstructions` please
`findRecipesWithInstructions` getRecipeDescription and findByIngredients and parse its responses

2021-12-31 17:13 UTC, janowsiany commented on src/services/SpoonacularService.js
> +    return data;
it is enough to 
```suggestion
    return response.json();
```

2022-01-02 21:05 UTC, natimati commented on src/services/SpoonacularService.js
> +    return recipesWithInstructions;
I think i understand what you meant.  I decided to create two methods: 
- findRecipesWithInstructions - which will return recipes with instructions, it will call findByIngredients and findRecipeDescription, and will be available outside 
- getRecipesWithInstructions - which will merge array responses from api calls in findByIngredients and findRecipeDescription
thanks to that fullfill single responsibility principle for all methods

2022-01-03 11:00 UTC, janowsiany requested changes
We can simpilfy it even further, take a look, what do you think?

2022-01-03 19:28 UTC, natimati commented on src/services/SpoonacularService.js
> +  }
You removed ""&includeInstruction=true";" but i think we should leave it in url - API will filter results for us. also it possible to have empty array if we dont iclude it, becouse we are filtering result later

2022-01-03 19:38 UTC, janowsiany approved these changes

2022-01-03 20:55 UTC, janowsiany commented on src/services/SpoonacularService.js
> +  }
If you say so ;), i could not find it in the docs

2022-01-04 11:17 UTC, merged